name: Test with Platformio

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y valgrind
          python -m pip install --upgrade pip
          pip install platformio
      - name: Test
        run: |
          pio test -e native -v
