name: Build simple-esp32 with ESP IDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: ${{ github.workspace }}/app

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.6
          target: esp32
          path: app/examples/simple-esp32-idf