name: Test with Platformio

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/bertmelis/pio-test-container

    services:
         mosquitto:
              image: eclipse-mosquitto
              ports:
                  - "1883:1883"
              volumes:
                  - ${{ github.workspace }}/.github/mosquitto:/mosquitto/config
              options: --name mosquitto

    steps:
      - uses: actions/checkout@v4
      - name: Restart MQTT
        # Restart MQTT after volumes have been checked out
        uses: docker://docker
        with:
          args: docker restart mosquitto
      - name: Test
        run: |
          pio test -e native -v