name: Test with Platformio

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/bertmelis/pio-test-container

    services:
         mosquitto:
              image: eclipse-mosquitto
              ports:
                  - "1883:1883"
              #volumes:
              #    - ${{ github.workspace }}/.github/etc/mosquitto.conf:/mosquitto/config/mosquitto.conf
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          pio test -e native -v